package com.videolibrary.db.videolibrary_db.entity.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE ActorBase PLEASE EDIT ../Actor.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the model of Actor object
 * 
 */
 
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;

import org.springframework.jdbc.core.RowMapper;
import com.videolibrary.db.videolibrary_db.entity.Actor;

public class ActorBase implements RowMapper<Actor>{
	
	private Long _id;
	
	// Attributes
	
	// Relations FilmObj
	private String FilmObj;
	
	
	
	@Override
	public Actor mapRow(ResultSet rs, int rowNum) throws SQLException {
		
		Actor obj = new Actor();
		try {
			obj.set_id(rs.getLong("id"));
			
        	
        	// Relations 1:m FilmObj
			obj.setFilmObj(rs.getString("FilmObj"));
        	
		}
		catch(Exception e) {
			e.printStackTrace();
		}
		return obj;
	}


	public Long get_id() {
		return _id;
	}

	public void set_id(Long _id) {
		this._id = _id;
	}
	
	
    
    // Relations 1:m FilmObj
	public String getFilmObj() {
		return FilmObj;
	}

	public void setFilmObj(String FilmObj) {
		this.FilmObj = FilmObj;
	}
    
    
    
    
}