package com.videolibrary.db.videolibrary_db.entity.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE FilmBase PLEASE EDIT ../Film.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the model of Film object
 * 
 */
 
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;

import org.springframework.jdbc.core.RowMapper;
import com.videolibrary.db.videolibrary_db.entity.Film;

public class FilmBase implements RowMapper<Film>{
	
	private Long _id;
	
	// Attributes
    private String Title;
    private Date Year;
	
	
	
	@Override
	public Film mapRow(ResultSet rs, int rowNum) throws SQLException {
		
		Film obj = new Film();
		try {
			obj.set_id(rs.getLong("id"));
			obj.setTitle(rs.getString("Title"));
			obj.setYear(rs.getDate("Year"));
			
        	
		}
		catch(Exception e) {
			e.printStackTrace();
		}
		return obj;
	}


	public Long get_id() {
		return _id;
	}

	public void set_id(Long _id) {
		this._id = _id;
	}
	
	public String getTitle() {
		return Title;
	}


	public void setTitle(String Title) {
		this.Title = Title;
	}
	public Date getYear() {
		return Year;
	}


	public void setYear(Date Year) {
		this.Year = Year;
	}
	
    
    
    
    
}